### ISSUE TITLE
CHEBI:16488 Wrong reference to HMDB

### ISSUE THREAD

**Issue by lptolik** [ebi-chebi/ChEBI#3963] opened 2020-11-12 17:54 UTC
Entries CHEBI:16488 and CHEBI:16026 have identical reference to HMDB: HMDB0001370; however, according to InChI, the only valid match is CHEBI:16026. 

Reference to HMDB0001370 should be removed from CHEBI:16488.

**Comment by amalik01** [comment] 2020-11-13 10:22
Now fixed. ChEBI usually maps to HMDB based on structures and synonyms. The issue is that although the HMDB structure matches CHEBI:16026. HMDB is all over the place is terms of synonyms, it has several synonyms which match CHEBI:16488. E.g. (2R,6S)-2,6-Diamino-heptanedioic acid.

**Closed by amalik01** 2020-11-13 10:22 UTC

**Comment by lptolik** [comment] 2020-11-13 10:31
Great, thank you.
