### ISSUE TITLE
parentage of spermidine etc

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#3420] opened 2018-02-08 09:16 UTC
from
https://github.com/geneontology/go-ontology/issues/14928

spermidine (and other polyamines)
are defined:

spermidine (CHEBI:16610) is conjugate base of spermidine(3+) (CHEBI:57834)
spermidine(3+) (CHEBI:57834) is a ammonium ion (CHEBI:35274)

but an ammonium ion is NH4. This causes problems in GO for example  spermidine transporters are classified as "ammonium transporters" from their logical definitions.

Could you take a look?

Thanks,

Val

**Comment by pgaudet** [comment] 2018-08-28 20:34
Hello CheBI curators, 


Can you please look at this ? 

Thanks, Pascale

**Comment by ValWood** [comment] 2018-10-01 13:14
Hello,

Any news on this one?

Thanks

Val

**Comment by ValWood** [comment] 2019-04-04 09:39
Hello, I have been asked if any news on this for the upcoming GO meeting. It is causing quite a lot of dodgy inferences for us. Is anyone available to take a look?

**Comment by kaxelsen** [comment] 2019-04-04 11:02
I would try to add a ticket in the ChEBI github queue https://github.com/ebi-chebi/ChEBI/issues and ask Adnan to look into this, as spermidine CHEBI:16610 is classified as a triamine (CHEBI:38751) which makes more sense. But I think it might be difficult to resolve as other poly ammonuium ions are also children of ammonium (CHEBI:35274), e.g. N-[(E)-4-ammoniobutylidene]propane-1,3-diaminium (CHEBI:58732),  (2E,5S,6E,8E,10E)-1-ammoniododeca-2,6,8,10-tetraen-5-ol (CHEBI:142545) and spermine(4+) (CHEBI:45725)

**Comment by amalik01** [comment] 2019-04-04 11:06
The previous curator who was suppose to be looking into this issue has now left. Let me take a look and i will get back to you. Adnan

**Comment by amalik01** [comment] 2019-04-08 13:36
The issue here is that biologists use NH4+ to mean ammonium ion whereas IUPAC names it as ammonium. In order to resolve this issue, we could possibly rename the ammonium ion (CHEBI:35274) class in ChEBI to aminium ion (which basically are substituted ammonium ions / cations which are formed by protonation of amines) that can be further subdivided into primary, secondary and tertiary aminium ions. This will then allow you to differentiate between the 2 classes.

BUT before I do this and upset a lot of our users, I will need to discuss this thoroughly with them since we have a lot of child classes under this category. I am also away for the next 3 weeks, and this is something which cannot be done straightaway without further discussion. I will let you know about the outcome in due course.

**Comment by ValWood** [comment] 2019-04-10 13:59
can the ticket be reopened until adressed?

**Comment by ValWood** [comment] 2019-04-10 14:02
The issue for us is that 

spermidine transmembrane transport
becomes is_a
ammonium transmembrane transport

**Comment by ValWood** [comment] 2019-08-09 17:26
Hi,
I'm not sure that the renaming would resolve the GO issue.
But we are still finding that spermidine transporters are  classified as ammonium transporters.

**Comment by cmungall** [comment] 2019-08-09 18:22
I think issues of nomenclature are a red herring. The protonation state is also a red herring. The issue is that CHEBI is confusing is-a and has-part. We used to have a lot of this prior to the initial alignment (e.g. nucleotide + carbohydrate).

Going back to the original reported issue from Feb 2018:

> spermidine(3+) (CHEBI:57834) is a ammonium ion (CHEBI:35274)

This cannot be correct. 

**We cannot have a structure C7HxN3 be a subclass of a structure NHx**. CHEBI must be using subClassOf in a way that contradicts the OWL definition of subClassOf. Either that, or the definitions and names of the classes are not clear, and CHEBI:35274 is intended to mean what might be called "ammonium ion containing compound".

I think the subClassOf needs to be changed to has-part here. This will fix the issue for GO, and for others who intend to use this branch of CHEBI to assist in classification.

Hopefully this issues can be resolved promptly. If there are any questions or disagreements, would it be possible for someone from CHEBI to join a GO ontology developer call to discuss? That would be very helpful. The group meets 5pm UK time on mondays. If this is not convenient we can find a different time.

**Comment by jannahastings** [comment] 2019-08-09 20:09
The definition of CHEBI:35274 does (now?) say NH4+ and derivatives, so it is clear that what is meant by that class is rather "ammonium ion containing compound". As Chris says, it would be best if this class could be separated from the class for NH4+ itself (the ammonium ion) which would then be related via has_part and not subClassOf.

**Comment by cmungall** [comment] 2019-08-09 20:29
Yes, that would work perfectly, GO needs the actual NH4+ class itself

**Comment by bpeters42** [comment] 2019-08-09 22:00
Just wanted to add that this is another good example where it would be preferable if Chebi had logical definitions with precise meanings to help dis-ambiguate the textual definitions.

**Comment by pgaudet** [comment] 2019-08-12 09:54
> The definition of CHEBI:35274 does (now?) say NH4+ and derivatives,

Does this solve GO's issue ? Spermidine will remain a is_a ammonium, won't it ?

**Comment by cmungall** [comment] 2019-08-12 15:45
>> The definition of CHEBI:35274 does (now?) say NH4+ and derivatives,
> Does this solve GO's issue ? Spermidine will remain a is_a ammonium, won't it ?

It clarifies that we should not use this when we say NH4+. It also clarifies that there is a gap in CHEBI for true NH4+

**Comment by amalik01** [comment] 2019-08-13 16:07
I have changed the ChEBI name of (CHEBI:35274) from ammonium ion to ammonium ion derivative which now has_parent_hydride ammonium, NH4+(CHEBI:28938). Both entries will now be distinguishable and hopefully this should resolve GO's issue.

In the chemistry community, ammonium ion derivatives (CHEBI:35274) are often referred to as ammonium ions so is it permissible to use this as a synonym?

**Comment by pgaudet** [comment] 2019-08-14 10:13
Hi @amalik01 

Could the definition of "ammonium ion derivative" be improved ? It now states: 
"Ammonium ion derivatives formed by substitution of ammonium, NH4+, by univalent groups." This sounds too general ? Ammonium being NH4+, it makes it sound like anything that does not contain NH4+ is an ammonium ion derivative (for example of you substitute NH4+ by a NaCl molecule you get NaCl; but how is that a derivative of ammonium ? 

I am also not sure that all children of "ammonium ion derivative" are univalent. 

Pascale

**Comment by amalik01** [comment] 2019-08-15 15:44
Definition has been updated.

Ammonium ion derivatives are usually univalent. Derivatives formed by substitution of NH4+ by groups having two or three free valencies on the same atom. Such derivatives are, where possible, designated by a specific class name (E.g. iminium ion).

**Comment by pgaudet** [comment] 2019-12-02 15:49
Can spermidine be an ammonium derivate rather than an 'is_a ammium'? We are still getting bad inferences. 

Thanks, Pascale

**Comment by cmungall** [comment] 2019-12-02 18:08
@amalik's change on Aug 13 resolved this issue.

Note the way in which the issue was fixed: the label of CHEBI:35274 changed from 'ammonium ion' to 'ammonium ion derivative'. My preference would have been to obsolete the ID to avoid confusion. 

Here is an example of a logical definition in GO:

```
id: GO:0072488
name: ammonium transmembrane transport
namespace: biological_process
def: "The process in which ammonium is transported across a membrane. Ammonium is the cation NH4+." [GOC:mah]
comment: Note that this term is not intended for use in annotating lateral movement within membranes.
synonym: "ammonium membrane transport" EXACT []
intersection_of: GO:0006810 ! transport
intersection_of: results_in_transport_across GO:0016020 ! membrane
intersection_of: transports_or_maintains_localization_of CHEBI:35274 ! ammonium ion
```

once we refresh the imports it will say `CHEBI:35274 ! ammonium ion derivative` which is clearly not what we intend

**Comment by cmungall** [comment] 2019-12-02 18:20
@amalik01:
> In the chemistry community, ammonium ion derivatives (CHEBI:35274) are often referred to as ammonium ions so is it permissible to use this as a synonym?

We would normally recommend different synonym scopes here, and creating different synonym types for different communities. However, for reasons I don't fully understand, CHEBI uses synonym scopes in different ways from other ontologies, and EXACT and RELATED do not mean the same thing.

**Comment by jannahastings** [comment] 2019-12-03 13:41
@cmungall  It used to be the case (the current team may correct me) that ChEBI did not annotate the distinction between exact and related synonyms in the curator tool, and therefore this information was appended with the creation of the ontology export following a simple computational rule: EXACT was reserved for systematic IUPAC names, while RELATED was chosen for all other synonyms. At the time of implementation this was considered the safest approach (to avoid calling a non-exact synonym exact by accident) in the absence of manual annotation of the distinction.

**Comment by cmungall** [comment] 2020-04-23 19:07
@amalik01 I think you can close this issue.

(I would prefer more metadata on the synonym and use of synonym scopes, but this is a separate issue)

**Comment by amalik01** [comment] 2020-04-27 09:01
To avoid any confusion, i have removed 'ammonium ions' and 'azanium ions' synonyms from ammonium ion derivative (CHEBI:35274).

**Closed by amalik01** 2020-04-27 09:01 UTC
