### ISSUE TITLE
chebi:58557, please update 2D structure

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3383] opened 2017-10-18 11:58 UTC
Dear ChEBI curators,

Please would you update the 2D structure of CHEBI:58557 with the attached molfile.
It is correct, but it's just to be consistent in the way we draw molecules.

Thanks for your time,

Cheers, Anne
[ChEBI_58557_updated.txt](https://github.com/ebi-chebi/ChEBI/files/1394486/ChEBI_58557_updated.txt)

**Comment by G-Owen** [comment] 2017-10-18 12:23
Hi Anne,
We are having problems adding new structures at the moment (hopefully this will be fixed shortly). But the structure in the attached molfile is actually the enantiomer of CHEBI:58557. 
ACD-Name names the current (Fischer projection) structure as
2-acetamido-2-deoxy-6-O-phosphonato-D-mannose
but it names the structure in your molfile as 
2-acetamido-2-deoxy-6-O-phosphonato-L-mannose.
Can you confirm whether you want the D- or the L- version?

Thanks,
Gareth

**Comment by amorgat** [comment] 2017-10-18 13:09
Hi Gareth,

Strange... 
I need N-acetyl-D-mannosamine 6-phosphate
The Rhea reaction is:
http://www.rhea-db.org/reaction?id=25253

I've just added a phopshate to CHEBI:17122 (N-acetyl-D-mannosamine). It should not change the stereochemistry???

**Comment by G-Owen** [comment] 2017-10-18 13:35
Hi Anne,

No - adding the phosphate won't change the D- or L- assignment. 

Unfortunately, the problem is that the 'zig-zag' structure for CHEBI:17122 is also wrong, but nobody has spotted the error in the 7 years since the (correct) Fischer projection structure was replaced as the default structure by the (incorrect) zig-zag structure!

I will sort the structures out as soon as the structure-editing problem has been fixed (hopefully later today). In the meanwhile, I will have a look and see if I can find any other problems arising from incorrect Fischer --> zig-zag conversions.

I will let you know when the structures are corrected (and also if I come across any more errors of this type.

Sorry for the inconvenience caused.

Gareth

**Comment by G-Owen** [comment] 2017-10-19 11:57
Hi Anne,

Now sorted. I didn't come across any other errors of this type, but I can't guarantee that there aren't any! 
Sorry again for the problems caused.

Kind regards,
Gareth

**Closed by G-Owen** 2017-10-19 11:57 UTC
