### ISSUE TITLE
R-mevalonolactone, (-)- should be renamed to R-mevalonolactone

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4338] opened 2023-02-16 17:49 UTC
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:67849

The name should be simplified and the entry "Mevalonlactone" without enantiomeric specification is missing.

**Comment by amalik01** [comment] 2023-02-22 14:13
Now fixed and a separate entry for the racemic mixture also created (CHEBI:194429)

**Closed as completed by amalik01** 2023-02-22 14:13 UTC

**Comment by sorenwacker** [comment] 2023-03-17 21:13
Would it be possible to add a SMILES string to the entry?

**Comment by amalik01** [comment] 2023-03-21 16:09
Racemic mixtures comprise of 2 enantiomers. Unfortunately the current ChEBI database is not able to depict 2 structures side-by-side and therefore racemate entries in ChEBI do not have a chemical structure associated with them. As a result, we are unable to generate a SMILES or InChI when no chemical structure is present. This is something we will need to fix at some stage.

**Comment by sorenwacker** [comment] 2023-03-21 22:57
My suggestion here is to use SMILES strings without specifying the orientation of the bonds.

Similar to structures 25350, 36464, and 18790.

**Comment by sorenwacker** [comment] 2023-03-21 23:04
And then I would add links 

18790 is_enantiomer of 25350
36464 is_enantiomer of 25350
18790 is_enantiomer of 36464 
36464 is_enantiomer of 18790 

However, 25350 is actually not a specific enantiomer and therefore has no such edges pointing to it.

**Comment by amalik01** [comment] 2023-03-23 11:51
Hi,

The ontology for CHEBI:25350 was incorrect and has now been fixed. This entry is also a racemic mixture. This entry was curated before the mixtures branch was introduced into ChEBI.

For racemic mixtures, we create 4 separate entries in ChEBI (one entry for the racemic mixture itself where we don't display any structures, one entry for the R-enantiomer, one entry for the S-enantiomer and one entry for a structure that has unspecified stereochemistry (here we show the structure without the wedge/dash bonds).

The unspecifed structure for mevalonolactone is CHEBI:95115 and has a SMILES string associated with it.

We used to treat 'unspecified stereochemistry' and 'racemates' as the same thing (as virtually all other databases do - they are generally depicted with the same (no stereobonds, wavy bonds, etc.) structure. The individual enantiomers were linked to this unspecified/racemate entity by is_a relationships. The problem is that both enantiomers inherit the roles of the racemate, whereas it is very common for individual enantiomers to activate or inhibit different receptors, etc.
Accordingly, when we developed the 'mixtures' branch of the ChEBI ontology, we split the 'unspecified' and 'racemic' versions of a molecule into separate entries. The individual enantiomers are linked to the unspecified version by is_a relationships, while the racemate is linked to the individual enantiomers by has_part relationships. This avoids each enantiomer inheriting the roles of the other. We generally give a long, IUPAC-name-type of ChEBI name for the unspecified version, and use the commonly-used drug names (etc.) for the racemate and the individual enantiomers.

**Comment by sorenwacker** [comment] 2023-04-07 21:30
Thank you, that clears things up. I will try to adjust my tool to this convention then. It would be helpful to have labels on specific nodes that specify, this is the human-readable name entry, this is the enantiomeric unspecific SMILES entry, or something along the lines.
